name: Publish AK.Enova.API

on:
  push:
    branches:
      - master

jobs:
  build-pack-publish:
    runs-on: windows-latest
    environment: NUGET_API_KEY

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build AK.Enova.API/AK.Enova.API.csproj -c Release --no-restore

    - name: Test
      run: dotnet test AK.Enova.API/AK.Enova.API.csproj -c Release --no-build
      continue-on-error: true

    - name: Pack
      run: dotnet pack AK.Enova.API/AK.Enova.API.csproj -c Release --no-build -o nupkg

    - name: Show packages
      run: Get-ChildItem -Recurse -Filter *.nupkg

    - name: Publish to NuGet
      run: dotnet nuget push nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
